{
  "openapi": "3.0.3",
  "info": {
    "title": "Swagger Peerly",
    "description": "Peer to peer appreciations",
    "version": "1.0.11"
  },
  "servers": [
    {
      "url": "http://localhost:33001/"
    }
  ],
  "tags": [
    {
      "name": "Core Values",
      "description": "Core Value cruds"
    }
  ],
  "paths": {
    "/core_values/{coreValueId}": {
      "put": {
        "tags": [
          "Core Values"
        ],
        "summary": "Update an existing core value",
        "description": "Update an existing core value by Id",
        "operationId": "updateCoreValue",
        "parameters": [
          {
            "name": "coreValueId",
            "in": "path",
            "description": "ID of corevalue",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 32
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Update an existing core value in the organisation",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCoreValues"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Invalid input data"
          },
          "404": {
            "description": "Core value id not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "get": {
        "tags": [
          "Core Values"
        ],
        "summary": "Finds corevalue by id",
        "description": "get a corevalue corevalue id",
        "operationId": "get a corevalue by id",
        "parameters": [
          {
            "name": "coreValueId",
            "in": "path",
            "description": "ID of corevalue",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 1
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GetCoreValuesResp"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Invalid core value id"
          }
        }
      }
    },
    "/core_values": {
      "post": {
        "tags": [
          "Core Values"
        ],
        "summary": "Add a new core value",
        "description": "Add a new core value",
        "operationId": "addCoreValue",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Create a new core value",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCoreValues"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successfully created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateCoreValuesResp"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "get": {
        "tags": [
          "Core Values"
        ],
        "summary": "List all corevalues of the organisation",
        "description": "List all the core values of the specified organisation",
        "operationId": "listCoreValues",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ListCoreValuesResp"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/appreciation/{id}": {
      "get": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "tags": [
          "Appreciation"
        ],
        "summary": "get appreciation by id",
        "description": "Display Appreciation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of appreciation",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 28
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AppreciationSuccessResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid input data",
                    "value": {
                      "success": false,
                      "message": "Invalid input data",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Appreciation not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Appreciation not found",
                    "value": {
                      "success": false,
                      "message": "appreciation not found",
                      "status": 404,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Appreciation"
        ],
        "summary": "Delete appreciation",
        "description": "Delete Appreciation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of appreciation",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 28
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Invalid input data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid input data",
                    "value": {
                      "success": false,
                      "message": "Invalid input data",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Appreciation not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Appreciation not found",
                    "value": {
                      "success": false,
                      "message": "appreciation not found",
                      "status": 404,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appreciation": {
      "post": {
        "tags": [
          "Appreciation"
        ],
        "summary": "Create appreciation",
        "description": "Create Appreciation",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAppreciation"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Create Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateAppreciationResp"
                }
              }
            }
          },
          "400": {
            "description": "Appreciation data is not valid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid Corevalue Id",
                    "value": {
                      "success": false,
                      "message": "invalid corevalue id",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Invalid Receiver Id",
                    "value": {
                      "success": false,
                      "message": "invalid receiver id",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-3": {
                    "summary": "Blank Description",
                    "value": {
                      "success": false,
                      "message": "Description cannot be blank",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Appreciation not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "User Not Found",
                    "value": {
                      "success": false,
                      "message": "User Not Found",
                      "status": 404,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Invalid corevalue data",
                    "value": {
                      "success": false,
                      "message": "Invalid corevalue data",
                      "status": 404,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appreciations": {
      "get": {
        "tags": [
          "Appreciation"
        ],
        "summary": "Get appreciation list",
        "description": "Get Appreciation",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": [
                "application/vnd.peerly.v1"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AppreciationsSuccessResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    },
    "schemas": {
      "UpdateCoreValues": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Updated core value"
          },
          "description": {
            "type": "string",
            "example": "updated description"
          }
        }
      },
      "CreateCoreValues": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Updated core value"
          },
          "description": {
            "type": "string",
            "example": "updated description"
          },
          "parent_core_value_id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          }
        }
      },
      "CreateCoreValuesResp": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "parent_core_value_id": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "GetCoreValuesResp": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "parent_core_value_id": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "ListCoreValuesResp": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "parent_core_value_id": {
            "type": "integer",
            "format": "int64"
          }
        }
      },

    "SuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "Appreciation": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 4
          },
          "core_value_name": {
            "type": "string",
            "example": "Integrity"
          },
          "description": {
            "type": "string",
            "example": "Great teamwork!"
          },
          "is_valid": {
            "type": "boolean",
            "example": true
          },
          "total_rewards": {
            "type": "integer",
            "example": 10
          },
          "quarter": {
            "type": "string",
            "example": 2
          },
          "sender_first_name": {
            "type": "string",
            "example": "John"
          },
          "sender_last_name": {
            "type": "string",
            "example": "Doe"
          },
          "sender_image_url": {
            "type": "string",
            "example": "https://example.com/profile_images/johndoe.jpg"
          },
          "sender_designation": {
            "type": "string",
            "example": "Software Engineer"
          },
          "receiver_first_name": {
            "type": "string",
            "example": "Jane"
          },
          "receiver_last_name": {
            "type": "string",
            "example": "Smith"
          },
          "receiver_image_url": {
            "type": "string",
            "example": "https://example.com/profile_images/janesmith.jpg"
          },
          "receiver_designation": {
            "type": "string",
            "example": "Product Manager"
          },
          "created_at": {
            "type": "integer",
            "example": 1719322966768
          },
          "updated_at": {
            "type": "integer",
            "example": 1719322966768
          }
        }
      },
      "AppreciationsSuccessResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/SuccessResponse"
          },
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Appreciation"
                }
              }
            }
          }
        ]
      },
      "AppreciationSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "Appreciation data got successfully"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "$ref": "#/components/schemas/Appreciation"
          }
        }
      },
      "CreateAppreciation": {
        "type": "object",
        "properties": {
          "core_value_id": {
            "type": "integer",
            "example": 1
          },
          "description": {
            "type": "string",
            "example": "Great teamwork"
          },
          "receiver": {
            "type": "integer",
            "example": 5
          }
        }
      },
      "CreateAppreciationResp": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Appreciation",
            "id": {
              "type": "integer",
              "example": 2
            },
            "core_value_id": {
              "type": "integer",
              "example": 1
            },
            "description": {
              "type": "string",
              "example": "Great teamwork"
            },
            "quarter": {
              "type": "integer",
              "example": 2
            },
            "sender": {
              "type": "integer",
              "example": 6
            },
            "receiver": {
              "type": "integer",
              "example": 5
            },
            "created_at": {
              "type": "integer",
              "example": 1719388759956
            },
            "updated_at": {
              "type": "integer",
              "example": 1719388759956
            }
          }
        }
      }
    }
  }
}